# ../docker-compose.yml

version: '3.9'

services:
  backend:
    container_name: app_backend
    build:
      context: .
      dockerfile: Dockerfile
    image: image-app_backend
    ports:
      - "3001:3001"
    working_dir: /app
    environment:
      - ALLOWED_ORIGIN=https://808a-189-71-214-150.ngrok-free.app
      - CLOUDINARY_CLOUD_NAME=dxdaxszow
      - CLOUDINARY_API_KEY=223998542144664
      - CLOUDINARY_API_SECRET=ndI3wHthK8cymKQS55gPUSiW610
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      interval: 30s
      timeout: 10s
      retries: 5
